# Generated by Django 4.1.13 on 2023-12-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='port',
            new_name='post',
        ),
    ]
